<?php

namespace AppBundle\Repository;

/**
 * SaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNbSaisons(){
        $results = $this->createQueryBuilder('saison')
            ->select('COUNT(saison)')
            ->getQuery()
            ->getSingleScalarResult();
        return $results;
    }

}
