# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12 #nb de boucle pour encoder

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            provider: our_db_provider


            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: security.login
                check_path: security.login
                default_target_path: backOffice
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            logout:
                path: security.logout
                target: /

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: /backOffice, roles: ROLE_ADMIN }